website/__init__.py
from flask import Flask, app

def create_app():

    # from <name_of_blueprint_folders> import <functions>
    from .routes import routes
    app = Flask(__name__)
    # app.register_blueprint
    app.register_blueprint(routes, url_prefix='/')

    return app

website/routes.py
from flask import Blueprint, render_template
from datetime import datetime
from pytz import timezone
from tzlocal import get_localzone
from newsapi import NewsApiClient
from dotenv import load_dotenv
import random
import os

import newsapi
load_dotenv()
API_KEY = os.getenv("API_KEY")

contact_points = {
    "email": "condrey.blake1217@gmail.com",
    "github": "https://github.com/blakecondrey",
    "linkedin": "https://www.linkedin.com/in/blakecondrey/",
    "portfolio": "http://www.blakecondrey.com"
}

rights = [
    "rights",
    "knights",
    "stalactites",
    "fights",
    "bytes",
    "stalagmites",
    "tights",
    "kites"
]

routes = Blueprint("routes", __name__, static_folder="static", 
                    template_folder="templates")


newsapi = NewsApiClient(api_key=API_KEY)

def grab_headlines(top_headlines):
    articles = top_headlines['articles']
    title = []
    desc = []
    img = []
    url = []
    for i in range(len(articles)):
        generated = articles[i]
        title.append(generated['title'])
        desc.append(generated['description'])
        img.append(generated['urlToImage'])
        url.append(generated['url'])
    output = zip(title, desc, img, url)
    
    return output

    # starting new function for time

def get_time():
    time_format = "%m/%d/%Y"
    date_time = datetime.now(timezone('UTC'))
    now_local = date_time.astimezone(get_localzone())
    time_now = now_local.strftime(time_format)

    return time_now

@routes.route('/')
def home():
    time_now = get_time()
    top_headlines = newsapi.get_top_headlines(language = 'en')
    output = grab_headlines(top_headlines)
    return render_template('index.html', context=output, 
                    contact = contact_points, 
                    right = random.choice(rights),
                    time = time_now)

@routes.route('/stonks')
def stonks():
    time_now = get_time()
    top_headlines = newsapi.get_everything(q = 'stocks', language = 'en',
                    sources = 'bbc-news, google-news, the-wall-street-journal')
    output = grab_headlines(top_headlines)
    return render_template('stonks.html', context = output, 
                    contact = contact_points,
                    right = random.choice(rights),
                    time = time_now)

@routes.route('/sports')
def sports():
    time_now = get_time()
    top_headlines = newsapi.get_everything(q = 'sports', language = 'en',
                    sources = 'google-news, espn')
    output = grab_headlines(top_headlines)
    return render_template('sports.html', context = output, 
                    contact = contact_points,
                    right = random.choice(rights),
                    time = time_now)

@routes.route('/florida-man')
def florida_man():
    time_now = get_time()
    top_headlines = newsapi.get_everything(qintitle = 'florida man',
                    language = 'en',
                    sources = 'fox-news, cnn, google-news')
    output = grab_headlines(top_headlines)
    return render_template('florida-man.html', context = output, 
                    contact = contact_points,
                    right = random.choice(rights),
                    time = time_now)

@routes.route('/climate-change')
def climate_change():
    time_now = get_time()
    top_headlines = newsapi.get_everything(q = 'climate change',
                    language = 'en',
                    sources = 'cnn, bbc-news, the-verge, google-news')
    output = grab_headlines(top_headlines)
    return render_template('climate-change.html', context = output, 
                    contact = contact_points,
                    right = random.choice(rights),
                    time = time_now)

@routes.route('/covid')
def covid():
    time_now = get_time()
    top_headlines = newsapi.get_everything(q = 'covid',
                    language = 'en')
    output = grab_headlines(top_headlines)
    return render_template('covid.html', context = output, 
                    contact = contact_points,
                    right = random.choice(rights),
                    time = time_now)

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NewsAggregator</title>
    <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename = 'imgs/apple-touch-icon.png') }}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename = 'imgs/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename = 'imgs/favicon-16x16.png') }}">
    <link rel="icon" href="{{ url_for('static', filename = 'imgs/android-chrome-192x192.png') }}">
    <link rel="stylesheet" <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
        rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
        crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/app.css') }}">
</head>
<body>
    <div class="container-fluid">
        <div class="container-fluid sticky-top">
            {% include 'navbar.html' %}
        </div>
        {% block content %}

        {% endblock %}
        <div class="container-fluid">
            {% include 'footer.html' %}
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>
    <script src="{{ url_for('static', filename='js/app.js') }}"></script>
    
</body>
</html>

website/templates/climate-change.html
{% extends 'base.html' %}
{% block content %}
<div class="row justify-content-center align-items-center">
    <div class="col-6 top-buffer text-center">
        <h1 class="d-sm-6 d-md-3">{{ time }}</h1>
    </div>
    <div class="col-6 top-buffer text-center">
        <h1 class="d-sm-6 d-md-3">Top Stories in Climate Change</h1>
    </div>
</div>
<center>
    <div class="container row equal-cols">
        {% for title, desc, img, url in context %}
        <!--started-->
        <div class="col-md-6 p-2 m-auto">
        <div class="card card-color shadow-lg">
            <img class="card-img-top img-fluid myimage" src="{{ img }}" alt="News">
            <div class="card-body">
                <a href="{{ url }}" target="_blank"><h3 class="card-title strong">{{ title }}</h3></a>
                <p class="card-text">{{ desc }}</p>
            </div>
        </div>
        </div>
        {% endfor %}
    </div>
</center>
{% endblock %}

website/templates/covid.html
{% extends 'base.html' %}
{% block content %}
<div class="row justify-content-center align-items-center">
    <div class="col-6 top-buffer text-center">
        <h1 class="d-sm-6 d-md-3">{{ time }}</h1>
    </div>
    <div class="col-6 top-buffer text-center">
        <h1 class="d-sm-6 d-md-3">Top Stories in COVID-19</h1>
    </div>
</div>
<center>
    <div class="container row equal-cols">
        {% for title, desc, img, url in context %}
        <!--started-->
        <div class="col-md-6 p-2 m-auto">
        <div class="card card-color shadow-lg">
            <img class="card-img-top img-fluid myimage" src="{{ img }}" alt="News">
            <div class="card-body">
                <a href="{{ url }}" target="_blank"><h3 class="card-title strong">{{ title }}</h3></a>
                <p class="card-text">{{ desc }}</p>
            </div>
        </div>
        </div>
        {% endfor %}
    </div>
</center>
{% endblock %}

website/templates/florida-man.html
{% extends 'base.html' %}
{% block content %}
<div class="row justify-content-center align-items-center">
    <div class="col-6 top-buffer text-center">
        <h1 class="d-sm-6 d-md-3">{{ time }}</h1>
    </div>
    <div class="col-6 top-buffer text-center">
        <h1 class="d-sm-6 d-md-3">Top Florida Man Stories</h1>
    </div>
</div>
<center>
    <div class="container row equal-cols">
        {% for title, desc, img, url in context %}
        <!--started-->
        <div class="col-md-6 p-2 m-auto">
        <div class="card card-color shadow-lg">
            <img class="card-img-top img-fluid myimage" src="{{ img }}" alt="News">
            <div class="card-body">
                <a href="{{ url }}" target="_blank"><h3 class="card-title strong">{{ title }}</h3></a>
                <p class="card-text">{{ desc }}</p>
            </div>
        </div>
        </div>
        {% endfor %}
    </div>
</center>
{% endblock %}

website/templates/footer.html
<footer class="page-footer">
    <div class="row text-center">
        <div class="col-md-6 copy">
            <button type="button" class="btn btn-outline-secondary">
                <a href="{{ contact.github }}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                    class="bi bi-github" viewBox="0 0 16 16">
                    <path
                        d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z" />
                </svg></a></button>
            <button type="button" class="btn btn-outline-secondary">
                <a href="{{ contact.linkedin }}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                    class="bi bi-linkedin" viewBox="0 0 16 16">
                    <path
                        d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854V1.146zm4.943 12.248V6.169H2.542v7.225h2.401zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248-.822 0-1.359.54-1.359 1.248 0 .694.521 1.248 1.327 1.248h.016zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016a5.54 5.54 0 0 1 .016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225h2.4z" />
                </svg></a></button>
            <button type="button" class="btn btn-outline-secondary">
                <a href="mailto:{{ contact.email }}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                    class="bi bi-envelope-fill" viewBox="0 0 16 16">
                    <path
                        d="M.05 3.555A2 2 0 0 1 2 2h12a2 2 0 0 1 1.95 1.555L8 8.414.05 3.555zM0 4.697v7.104l5.803-3.558L0 4.697zM6.761 8.83l-6.57 4.027A2 2 0 0 0 2 14h12a2 2 0 0 0 1.808-1.144l-6.57-4.027L8 9.586l-1.239-.757zm3.436-.586L16 11.801V4.697l-5.803 3.546z" />
                </svg></a></button>
        </div>
        <div class="col-md-6 copy">
            <p>Copyright © 2021 | Blake Condrey | all
                {% if right %}
                    {{ right }}
                {% else %}
                    rights
                {% endif %}
                 reserved
            </p>
        </div>
    </div>
</footer>

website/templates/index.html
{% extends 'base.html' %}
{% block content %}
<div class="row justify-content-center align-items-center">
    <div class="col-6 top-buffer text-center">
        <h1 class="d-sm-6 d-md-3">{{ time }}</h1>
    </div>
    <div class="col-6 top-buffer text-center">
        <h1 class="d-sm-6 d-md-3">World News Today</h1>
    </div>
</div>
<center>
    <div class="container row equal-cols">
        {% for title, desc, img, url in context %}
        <!--started-->
        <div class="col-md-6 p-2 m-auto">
        <div class="card card-color shadow-lg">
            <img class="card-img-top img-fluid myimage" src="{{ img }}" alt="News">
            <div class="card-body">
                <a href="{{ url }}" target="_blank"><h3 class="card-title strong">{{ title }}</h3></a>
                <p class="card-text">{{ desc }}</p>
            </div>
        </div>
        </div>
        {% endfor %}
    </div>
</center>
{% endblock %}

website/templates/navbar.html
<div class="container-fluid">
    <nav class="navbar navbar-expand-lg navbar-light">
        <a href="{{ contact.portfolio }}" class="navbar-brand">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                class="bi bi-code-slash code-icon" viewBox="0 0 16 16">
                <path
                    d="M10.478 1.647a.5.5 0 1 0-.956-.294l-4 13a.5.5 0 0 0 .956.294l4-13zM4.854 4.146a.5.5 0 0 1 0 .708L1.707 8l3.147 3.146a.5.5 0 0 1-.708.708l-3.5-3.5a.5.5 0 0 1 0-.708l3.5-3.5a.5.5 0 0 1 .708 0zm6.292 0a.5.5 0 0 0 0 .708L14.293 8l-3.147 3.146a.5.5 0 0 0 .708.708l3.5-3.5a.5.5 0 0 0 0-.708l-3.5-3.5a.5.5 0 0 0-.708 0z" />
            </svg></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
            <div class="navbar-nav align-items-end mt-4">
                <!-- TO DO: FIX URL_FORS to match routes -->
                <a href="{{ url_for('routes.home') }}"" class=" nav-link px-lg-4">World News</a>
                <a href="{{ url_for('routes.stonks') }}" class="nav-link px-lg-4">Stocks</a>
                <a href="{{ url_for('routes.sports') }}" class="nav-link px-lg-4">Sports</a>
                <a href="{{ url_for('routes.covid') }}" class="nav-link px-lg-4">COVID-19</a>
                <a href="{{ url_for('routes.climate_change') }}" class="nav-link px-lg-4">Climate Change</a>
                <a href="{{ url_for('routes.florida_man') }}" class="nav-link px-lg-4">Florida Man</a>
            </div>
        </div>
    </nav>
</div>

website/templates/sports.html
{% extends 'base.html' %}
{% block content %}
<div class="row justify-content-center align-items-center">
    <div class="col-6 top-buffer text-center">
        <h1 class="d-sm-6 d-md-3">{{ time }}</h1>
    </div>
    <div class="col-6 top-buffer text-center">
        <h1 class="d-sm-6 d-md-3">Top Stories in Sports</h1>
    </div>
</div>
<center>
    <div class="container row equal-cols">
        {% for title, desc, img, url in context %}
        <!--started-->
        <div class="col-md-6 p-2 m-auto">
        <div class="card card-color shadow-lg">
            <img class="card-img-top img-fluid myimage" src="{{ img }}" alt="News">
            <div class="card-body">
                <a href="{{ url }}" target="_blank"><h3 class="card-title strong">{{ title }}</h3></a>
                <p class="card-text">{{ desc }}</p>
            </div>
        </div>
        </div>
        {% endfor %}
    </div>
</center>
{% endblock %}

website/templates/stonks.html
{% extends 'base.html' %}
{% block content %}
<div class="row justify-content-center align-items-center">
    <div class="col-6 top-buffer text-center">
        <h1 class="d-sm-6 d-md-3">{{ time }}</h1>
    </div>
    <div class="col-6 top-buffer text-center">
        <h1 class="d-sm-6 d-md-3">Stock Market Headlines</h1>
    </div>
</div>
<center>
    <div class="container row equal-cols">
        {% for title, desc, img, url in context %}
        <!--started-->
        <div class="col-md-6 p-2 m-auto">
        <div class="card card-color shadow-lg">
            <img class="card-img-top img-fluid myimage" src="{{ img }}" alt="News">
            <div class="card-body">
                <a href="{{ url }}" target="_blank"><h3 class="card-title strong">{{ title }}</h3></a>
                <p class="card-text">{{ desc }}</p>
            </div>
        </div>
        </div>
        {% endfor %}
    </div>
</center>
{% endblock %}